/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.HotelAdminRole;

import userinterface.CustomerRole.*;
import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Hotel.Hotel;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Samarth
 */
public class HotelCart extends javax.swing.JPanel {

    /**
     * Creates new form HotelCart
     */
    private JPanel userProcessContainer;
    EcoSystem ecosystem;
    DefaultTableModel grocModel;
    private UserAccount userAccount;
    DefaultTableModel foodModel;
    DefaultTableModel legalModel;
    DefaultTableModel eventModel;
    DefaultTableModel therapyModel;
    Hotel cust;
    JSplitPane screen;
    Double Total;
    Double Sum;

    public HotelCart(JPanel userProcessContainer, UserAccount account, EcoSystem system, JSplitPane screen, Hotel cust) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.screen = screen;
        this.userAccount = account;
        this.cust = cust;
        ecosystem = system;

        createTableModel();
        populateCustomerOrders();
    }

    public void populateCustomerOrders() {
        //Legal
        for (int i = legalModel.getRowCount() - 1; i >= 0; i--) {
            legalModel.removeRow(i);
        }
        for (int i = 0; i < cust.getLegaldirectorylist().size(); i++) {
            legalModel.addRow(new Object[]{
                i + 1,
                cust.getLegaldirectorylist().get(i).getStatus(),
                cust.getLegaldirectorylist().get(i).getLegal().getName()
            });
        }
        //grocery
        for (int i = grocModel.getRowCount() - 1; i >= 0; i--) {
            grocModel.removeRow(i);
        }
        for (int i = 0; i < cust.getOrderDirectoryList().size(); i++) {
            grocModel.addRow(new Object[]{
                i + 1,
                cust.getOrderDirectoryList().get(i).getStatus(),
                cust.getOrderDirectoryList().get(i).getRestaurant().getName()
            });

        }
        // restuarant
        for (int i = eventModel.getRowCount() - 1; i >= 0; i--) {
            eventModel.removeRow(i);
        }
        for (int i = 0; i < cust.getEventdirectorylist().size(); i++) {
            eventModel.addRow(new Object[]{
                i + 1,
                cust.getEventdirectorylist().get(i).getStatus(),
                cust.getEventdirectorylist().get(i).getHospitalManager().getName()
            });
        }

        for (int i = therapyModel.getRowCount() - 1; i >= 0; i--) {
            therapyModel.removeRow(i);
        }

        for (int i = foodModel.getRowCount() - 1; i >= 0; i--) {
            foodModel.removeRow(i);
        }
//        for (int i = 0; i < cust.ge.size(); i++) {
//            foodModel.addRow(new Object[]{
//                i + 1,
//                cust.getHotelorderDirectoryList().get(i).getStatus(),
//                cust.getHotelorderDirectoryList().get(i).getRestaurant().getName()
//            });
//
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        restListTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        restListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Location", "Phone No", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(restListTable);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 83, 170));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Grocery Order");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 83, 170));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable restListTable;
    // End of variables declaration//GEN-END:variables

    private void createTableModel() {
        grocModel = new DefaultTableModel();
        restListTable.setModel(grocModel);
        grocModel.addColumn("Id");
        grocModel.addColumn("Status");
        grocModel.addColumn("Grcoery Store Name");

        foodModel = new DefaultTableModel();
//        restListTable1.setModel(foodModel);
        foodModel.addColumn("Id");
        foodModel.addColumn("Status");
        foodModel.addColumn("Restaurant Name");

        legalModel = new DefaultTableModel();
        //legalTable.setModel(legalModel);
        legalModel.addColumn("Id");
        legalModel.addColumn("Status");
        legalModel.addColumn("Legal Company Name");

        eventModel = new DefaultTableModel();
       // restListTable3.setModel(eventModel);
        eventModel.addColumn("Id");
        eventModel.addColumn("Status");
        eventModel.addColumn("HouseHelp Name");

        therapyModel = new DefaultTableModel();
//        restListTable4.setModel(therapyModel);
        therapyModel.addColumn("Id");
        therapyModel.addColumn("Status");
        therapyModel.addColumn("Therapist Name");
    }

    private void populateTable() {
        if (cust.getOrderDirectoryList().size() > 0) {
            for (int i = grocModel.getRowCount() - 1; i >= 0; i--) {
                grocModel.removeRow(i);
            }
            int index = (cust.getOrderDirectoryList().size()) - 1;
            for (int i = 0; i < cust.getOrderDirectoryList().get(index).getOrderList().size(); i++) {
                Total = 0.0;
//                Total = Double.parseDouble(cust.getOrderDirectoryList().get(index).getOrderList().get(i).getPrice()) * cust.getOrderDirectoryList().get(index).getOrderList().get(i).getQuantity();
                Sum += Total;
                grocModel.addRow(new Object[]{
                    cust.getOrderDirectoryList().get(index).getId(),
                    cust.getOrderDirectoryList().get(index).getOrderList().get(i).getItem(),
                    cust.getOrderDirectoryList().get(index).getOrderList().get(i).getItem(),
                    cust.getOrderDirectoryList().get(index).getOrderList().get(i).getPrice(),
                    cust.getOrderDirectoryList().get(index).getOrderList().get(i).getQuantity(),
                    Total
                });
            }
        }
    }
//        if (cust.getHotelorderDirectoryList().size() > 0) {
//            for (int i = grocModel.getRowCount() - 1; i >= 0; i--) {
//                grocModel.removeRow(i);
//            }}}

//int index = (cust.getOrderDirectoryList().size()) - 1;
//            for (int i = 0; i < cust.getOrderDirectoryList().get(index).getOrderList().size(); i++) {
//                Total = 0.0;
////                Total = Double.parseDouble(cust.getOrderDirectoryList().get(index).getOrderList().get(i).getPrice()) * cust.getOrderDirectoryList().get(index).getOrderList().get(i).getQuantity();
//                Sum += Total;
//                grocModel.addRow(new Object[]{
//                    cust.getOrderDirectoryList().get(index).getId(),
//                    cust.getOrderDirectoryList().get(index).getOrderList().get(i).getItem(),
//                    cust.getOrderDirectoryList().get(index).getOrderList().get(i).getItem(),
//                    cust.getOrderDirectoryList().get(index).getOrderList().get(i).getPrice(),
//                    cust.getOrderDirectoryList().get(index).getOrderList().get(i).getQuantity(),
//                    Total
//                });
//            }
//        }
//    }
}
