/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.HotelAdminRole;

import userinterface.CustomerRole.*;
import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Hotel.Hotel;
import Business.Orders.OrderDirectory;

import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.GroceryAdminRole.ManageGroceryInventoryPanel;
import userinterface.GroceryAdminRole.ManageOrdersPanel;

/**
 *
 * @author  Samarth
 */
public class OtherServicesWorkArea extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    EcoSystem ecosystem;
    DefaultTableModel model1;
    private UserAccount userAccount;
    private OrderDirectory orderDirectory;
    DefaultTableModel model;
    Hotel cust;
    public OtherServicesWorkArea(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        ecosystem = system;
        cust = findManageHotel();


        //valueLabel.setText(enterprise.getName());
       // title2.setText("Welcome "+ cust.getName());
        
        ImageIcon icon1 =  new ImageIcon("./src/images/customer_panel_profile.png");
        Image image1 = icon1.getImage().getScaledInstance(75, 50, Image.SCALE_SMOOTH);
//        CovidCare1.setIcon(new ImageIcon(image1));
        
        ImageIcon icon2 =  new ImageIcon("./src/images/forbidden.png");
        Image image2 = icon2.getImage().getScaledInstance(75, 60, Image.SCALE_SMOOTH);
        legalbutton.setIcon(new ImageIcon(image2));
        
        ImageIcon icon3 =  new ImageIcon("./src/images/grocery_customer_panel.png");
        Image image3 = icon3.getImage().getScaledInstance(75, 30, Image.SCALE_SMOOTH);
        grocerybutton.setIcon(new ImageIcon(image3));
        
        ImageIcon icon4 =  new ImageIcon("./src/images/cutomer_panel_maid1.png");
        Image image4 = icon4.getImage().getScaledInstance(75, 50, Image.SCALE_SMOOTH);
        maidbutton.setIcon(new ImageIcon(image4));
        
        ImageIcon icon5 =  new ImageIcon("./src/images/customer_panel_therepist.png");
        Image image5 = icon5.getImage().getScaledInstance(75, 50, Image.SCALE_SMOOTH);
//        therpistbutton.setIcon(new ImageIcon(image5));
        
        ImageIcon icon6 =  new ImageIcon("./src/images/customer_panel_hotel.png");
        Image image6 = icon6.getImage().getScaledInstance(75, 40, Image.SCALE_SMOOTH);
//        hotelbutton.setIcon(new ImageIcon(image6));
        
        ImageIcon icon7 =  new ImageIcon("./src/images/customer_panel_cart.png");
        Image image7 = icon7.getImage().getScaledInstance(75, 60, Image.SCALE_SMOOTH);
        cartbutton.setIcon(new ImageIcon(image7));
        
        ImageIcon icon8 =  new ImageIcon("./src/images/customer_panel_payment.png");
        Image image8 = icon8.getImage().getScaledInstance(75, 60, Image.SCALE_SMOOTH);
        cardbutton.setIcon(new ImageIcon(image8));
        
        ImageIcon icon9 =  new ImageIcon("./src/images/PicsArt_12-11-06.26.57.jpg");
        Image image9 = icon9.getImage().getScaledInstance(250, 260, Image.SCALE_SMOOTH);
        birdiemessage.setIcon(new ImageIcon(image9));
        
        
 }
    
     public Customer findCustomer() {
        for (int i = 0; i < ecosystem.getCustomerDirectory().getCustomerList().size(); i++) {
            if (ecosystem.getCustomerDirectory().getCustomerList().get(i).getAccountDetails().getUsername().equals(this.userAccount.getUsername())) {
                return ecosystem.getCustomerDirectory().getCustomerList().get(i);
            }
        }
        return null;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        legalbutton = new javax.swing.JButton();
        grocerybutton = new javax.swing.JButton();
        maidbutton = new javax.swing.JButton();
        cartbutton = new javax.swing.JButton();
        cardbutton = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        birdiemessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(10);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        legalbutton.setBackground(new java.awt.Color(0, 0, 0));
        legalbutton.setForeground(new java.awt.Color(255, 255, 255));
        legalbutton.setText("Legal");
        legalbutton.setBorder(null);
        legalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legalbuttonActionPerformed(evt);
            }
        });

        grocerybutton.setBackground(new java.awt.Color(0, 0, 0));
        grocerybutton.setForeground(new java.awt.Color(255, 255, 255));
        grocerybutton.setText("Grocery");
        grocerybutton.setBorder(null);
        grocerybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grocerybuttonActionPerformed(evt);
            }
        });

        maidbutton.setBackground(new java.awt.Color(0, 0, 0));
        maidbutton.setForeground(new java.awt.Color(255, 255, 255));
        maidbutton.setText("Household");
        maidbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maidbuttonActionPerformed(evt);
            }
        });

        cartbutton.setBackground(new java.awt.Color(0, 0, 0));
        cartbutton.setForeground(new java.awt.Color(255, 255, 255));
        cartbutton.setText("Cart");
        cartbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartbuttonActionPerformed(evt);
            }
        });

        cardbutton.setBackground(new java.awt.Color(0, 0, 0));
        cardbutton.setForeground(new java.awt.Color(255, 255, 255));
        cardbutton.setText("Add Card");
        cardbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardbuttonActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(102, 102, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(legalbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grocerybutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maidbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(cartbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(legalbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(grocerybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maidbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cartbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cardbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(520, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        container.setBackground(new java.awt.Color(255, 255, 204));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        birdiemessage.setText(" ");
        container.add(birdiemessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        jSplitPane1.setRightComponent(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void legalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legalbuttonActionPerformed
        HotelOrderLegalPanel mm = new HotelOrderLegalPanel(userProcessContainer, userAccount,ecosystem, jSplitPane1);
//        userProcessContainer.add("manageNetworkJPanel",mm);
//        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);        // TODO add your handling code here:
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_legalbuttonActionPerformed

    private void grocerybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grocerybuttonActionPerformed
        OrderGroceryPanel mm = new OrderGroceryPanel(userProcessContainer, userAccount, ecosystem, jSplitPane1);
//        userProcessContainer.add("manageNetworkJPanel",mm);
//        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
        // TODO add your handling code here:        // TODO add your handling code here:
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_grocerybuttonActionPerformed

    private void maidbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maidbuttonActionPerformed
        HotelOrderEventPanel mm = new HotelOrderEventPanel(userProcessContainer, userAccount, ecosystem, jSplitPane1);
//        userProcessContainer.add("manageNetworkJPanel",mm);
//        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);        // TODO add your handling code here:
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_maidbuttonActionPerformed

    private void cartbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartbuttonActionPerformed
        // TODO add your handling code here:
        HotelCart mm = new HotelCart(userProcessContainer, userAccount, ecosystem, jSplitPane1 , cust);
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_cartbuttonActionPerformed

    private void cardbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardbuttonActionPerformed
        // TODO add your handling code here:
        HotelAddCardDetailsPanel mm = new HotelAddCardDetailsPanel(userProcessContainer, userAccount, cust,ecosystem, jSplitPane1);
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_cardbuttonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminWorkAreaJPanel dm= new AdminWorkAreaJPanel(userProcessContainer, userAccount, ecosystem);
        userProcessContainer.add("manageNetworkJPanel",dm);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


     public Hotel findManageHotel() {
        for(int i = 0; i < ecosystem.getHotel_Directory().getHotelList().size(); i ++) {
            if(ecosystem.getHotel_Directory().getHotelList().get(i).getUserAccount().getUsername().equals(this.userAccount.getUsername())) {
                return ecosystem.getHotel_Directory().getHotelList().get(i);
            }
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birdiemessage;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton cardbutton;
    private javax.swing.JButton cartbutton;
    private javax.swing.JPanel container;
    private javax.swing.JButton grocerybutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton legalbutton;
    private javax.swing.JButton maidbutton;
    // End of variables declaration//GEN-END:variables
}
